---
- name: Deploy dot net core application
  hosts: all
  tasks:
   - name: create new project
     command: dotnet new console -n MyConsoleApp -o myApp --force
   - name: Write the code
     copy:
      src: /root/dn/myapp.cs
      dest: /root/myApp/Program.cs
      remote_src: true
   - name: Run .net core app
     command: dotnet run -p /root/myApp/MyConsoleApp.csproj
